//
// Generated file, do not edit! Created by nedtool 5.7 from newVal.msg.
//

#ifndef __NEWVAL_M_H
#define __NEWVAL_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>newVal.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet NewVal
 * {
 *     int newDim;
 * }
 * </pre>
 */
class NewVal : public ::omnetpp::cPacket
{
  protected:
    int newDim;

  private:
    void copy(const NewVal& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NewVal&);

  public:
    NewVal(const char *name=nullptr, short kind=0);
    NewVal(const NewVal& other);
    virtual ~NewVal();
    NewVal& operator=(const NewVal& other);
    virtual NewVal *dup() const override {return new NewVal(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNewDim() const;
    virtual void setNewDim(int newDim);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NewVal& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NewVal& obj) {obj.parsimUnpack(b);}


#endif // ifndef __NEWVAL_M_H

